name: "Automated Deployment Pipeline"

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-gcp-cloud-v1
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Clone Code Repository
        uses: actions/checkout@v4

      - name: Install Terraform Engine on Runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.1

      - name: Initialize Workspace
        run: terraform init

      - name: Format Check
        run: terraform fmt -check

      - name: Execute and Build (Terraform Apply)
        run: terraform apply -auto-approve